# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_auto_20171001_1637'),
        ('accounts', '0002_profileimage_status_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ITM', 'Item'), ('IMG', 'Image')], max_length=10)),
                ('comment', models.TextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='items.Image')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='items.Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='accounts.Profile')),
            ],
        ),
    ]
