# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profileimage_status_main'),
        ('comments', '0002_auto_20171002_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.ProfileImage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_type',
            field=models.CharField(choices=[('PRF', 'Profile Image'), ('ITM', 'Item'), ('IMG', 'Image')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.Profile'),
        ),
    ]
