# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('comments', '0003_auto_20171005_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_type',
            field=models.CharField(choices=[('PRF', 'Profile Image'), ('ITM', 'Item'), ('IMG', 'Image'), ('GRP', 'Group')], max_length=3),
        ),
    ]
