# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileimage_status_main'),
        ('items', '0002_image_status_main'),
        ('likes', '0002_auto_20170925_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='items.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='items.Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_likes', to='accounts.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='image',
        ),
        migrations.RemoveField(
            model_name='like',
            name='item',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
