# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20170925_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelike',
            old_name='image',
            new_name='item',
        ),
    ]
