# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profileimage_status_main'),
        ('likes', '0005_commentlike_replylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='accounts.ProfileImage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image_likes', to='accounts.Profile')),
            ],
        ),
    ]
