# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status_main',
            field=models.BooleanField(default=False),
        ),
    ]
