# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_image_status_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=items.models.scramble_uploaded_image),
        ),
    ]
