# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 22:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20171001_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=['happy', 'forever'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=['please', 'happy', 'phillip'], size=None),
            preserve_default=False,
        ),
    ]
